# Generated by Django 4.2.17 on 2024-12-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=1.0, max_digits=1),
        ),
    ]
